application:

pcip:
  xpath:
    parcelId: //ShippingParameter[Name/text()="Parcel.RefNo"]/Value/text()
    clientId: //ShippingParameter[Name/text()="KN.ClientID"]/Value/text()
    warehouseId: //ShippingParameter[Name/text()="KN.Warehouse"]/Value/text()
    shipmentRefno: //ShippingParameter[Name/text()="Shipment.RefNo"]/Value/text()
    knSscc: //ShippingParameter[Name/text()="KN.SSCC"]/Value/text()
    knLoadId: //ShippingParameter[Name/text()="KN.LoadID"]/Value/text()
    knCarrierId: //ShippingParameter[Name/text()="KN.CarrierID"]/Value/text()
  parcel:
    identifier: "Parcel.Identcode"
    externalRefs: "Shipment.Status"
    refno: "Parcel.RefNo"
  authHeader:
    culture: en-US
    user: kncl01
    password: kncl01
  jaxb:
    contextPath: "kn.swift.ms.pcip.dto"
  basePath: /ws/cws/
  authBasePath: /ws/auth/login
wms:
  api:
    url: https://denotsl454.int.kn:8010
    user: kn_stig_api
    password: a888aeb95486f45919bd82e7aa56287e
  jms:
    broker: tcp://localhost:61616
    destination: mailbox2
esb:
    url: http://localhost:9098/mockKNCL01/ws
    pcipBasePath: /PCIP_ESB
    user: user
    password: password
server:
    port: 9091
